# Generated by Django 2.2 on 2023-01-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'категория товаров', 'verbose_name_plural': 'категории товаров'},
        ),
    ]
